version: '3.8'

services:
  app:
    build:
      dockerfile: local.Dockerfile
    restart: always
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  db:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: onlib
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234

  redis:
    image: redis
    ports:
      - "6378:6379"

#  migrator:
